### ISSUE TITLE
'charmap' codec can't encode character '\u0107' in position 39394: character maps to <undefined>

### ISSUE THREAD

**Issue by danielp3011** [jcontini/facebook-scraper#16]
I got the following error while doing just the indexing with "python make.py --index": error message: "'charmap' codec can't encode character '\u0107' in position 39394: character maps to <undefined>"
I guess it happens because one of my friends has a "Ö" in his name.

Can somebody help me with that?

Thanks a lot

**Comment by natejgardner** [comment]
this happens on Windows because of its super, super outdated codepages system. To fix it, go to region settings -> additional date, time & regional settings -> Region -> Administrative -> Change System Locale and check the box for Beta: Use Unicode UTF-8 for worldwide language support. You'll then need to reboot. Afterward, you won't have this issue.

**Comment by jcontini** [comment]
Hi @danielp3011, did that solve the issue for you? Please try to download latest version of the script, get latest Chrome Beta (has to be beta due to the way chrome-binary works), and then run `pipenv install` to set up latest dependencies.

@natejgardner do you know if there's a way I can address Daniel's problem in the script itself, so that Windows users don't need to take this step?

**Comment by danielp3011** [comment]
hi @jcontini ,
yes the solution from @natejgardner worked, thanks for that!
However now I get a new error. I will open a new issue.
