### ISSUE TITLE
Thanks, few findings and comments 

### ISSUE THREAD

**Issue by alanaberdeen** [jcontini/facebook-scraper#3]
Hi, 

Thanks for this, only used the tagged photos script so far but I got it working pretty easily and it did the job! 

Thought I'd leave a few observations here if you're thinking about changes, I'd be happy to help out a bit if I can find some time - let me know if that would be useful!

**1) Extracting img_id**
This failed for me a few times. I tracked the problem to being cases where the `fb_url` did not contain `'fbid='` and hence the code broke when trying to assign the variable. I think the url has a different structure when the photo was uploaded by a Facebook _Page_ rather than a Facebook _User_. Something to look into maybe... I got around it by just doing a check on the string first and assigning a default string if there were issues but I imagine there are far more elegant ways!

**2) Finding the Photos Button**
On a friends account, for some reason or another, the Photos shortcut button was not visible by default. This meant that it could not be found via `"navItem_2305272732"` and again things blew up. The temporary work around was going straight to the url `"https://www.facebook.com/USERNAME/photos"` instead. I hard coded this for the moment but perhaps the code could extract the users username and then Navigate to the page via the url rather than the HTML button... might be a bit more resistant to Facebook refactoring their code too.

Again thanks a bunch

**Comment by jcontini** [comment]
Hi @alanaberdeen !

Thanks so much for trying out the script and the great writeup. Apologies I'm just seeing your comment now. I think you caught my first iteration - I've since made several improvements to account for some of the edge cases you mentioned (including extracting img_id), added improved EXIF data writing, and fixed some issues where the metadata would get out of sync with the photo.

I just split this out to a separate repository: https://github.com/jcontini/fb-photo-downloader

Would you be keen to collaborate there? I'll plan to update the script to navigate to the photos page in the method you mentioned. But if you do beat me to it, feel free to submit a pull request. Thanks so much!

**Comment by alanaberdeen** [comment]
Great, good stuff! 
I'll have a dig around in the new repo
